language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1
install:
  - dotnet restore
branches:
  only:    
    - develop
before_script:
  - chmod -R a+x scripts/travis
script:
  - ./scripts/travis/build.sh
notifications:
  email:
    on_success: never
    on_failure: always