language: csharp
mono: none
dist: xenial
dotnet: 3.1
branches:
  only:    
    - develop
before_script:
  - chmod -R a+x scripts/travis
script:
  - ./scripts/travis/build.sh
after_success:
  - ./scripts/travis/dockerize.sh
notifications:
  email:
    on_success: never
    on_failure: always