#!/bin/bash
TAG=''
BUILD_NO=

case "$GIT_BRANCH" in
  "dev")
    TAG=dev
    BUILD_NO=$TRAVIS_BUILD_NUMBER
    ;;  
esac

echo $REPOSITORY:$TAG
echo $REPOSITORY:$BUILD_NO
echo $GIT_BRANCH

docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
docker build -t $DOCKER_REPOSITORY:$TAG -t $DOCKER_REPOSITORY:$BUILD_NO -t $DOCKER_REPOSITORY:$TAG-$BUILD_NO .
docker push $DOCKER_REPOSITORY:$TAG-$BUILD_NO