#!/bin/bash
TAG=''

case "$GIT_BRANCH" in
  "dev")
    TAG=dev    
    ;;  
esac

echo $REPOSITORY:$TAG
echo $REPOSITORY:$TRAVIS_BUILD_NUMBER
echo $GIT_BRANCH

docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
docker build -t $DOCKER_REPOSITORY:$TAG -t $DOCKER_REPOSITORY:$TRAVIS_BUILD_NUMBER -t $DOCKER_REPOSITORY:$TAG-$TRAVIS_BUILD_NUMBER .
docker push $DOCKER_REPOSITORY:$TAG-$TRAVIS_BUILD_NUMBER